### ISSUE TITLE
Live Only shows blank page

### ISSUE THREAD

**Issue by mfoland** [akrherz/live#21]
When I load up the installation that I created for live, it loads up blank. I was looking at the nws source code and it shows the time files. Is this the issue, and if so how do the files create and update the time? Check out http://usawxchat.usaweather.org/live I have an XMPP server with openfire that we created on our server. The Chat server works perfect with pidgin but not live.

**Comment by akrherz** [comment]
I should remove that ugly hack, the magic was happening due to an apache rewrite...

        # hacky means to keep browsers from caching important javascript
        RewriteRule ^/live/100/([0-9]+)\.js /live/live.js [L]
        RewriteRule ^/live/101/([0-9]+)\.js /live/js/MapPanel.js [L]

So I'll use this ticket to remove that code now.  It is not really necessary anymore
