### ISSUE TITLE
Little to no rooms to be able to chat in.

### ISSUE THREAD

**Issue by Arch881010** [akrherz/live#41]
Spotter chats are spotter chats, I believe I should be able to send a message there, not in any rush, but it feels iffy not being able to send messages and forced to read only mode. (Even if I am the only one online.)
![image](https://github.com/akrherz/live/assets/111789310/09df56ae-573f-41f3-9cce-913ab5dac108)

**Comment by Arch881010** [comment]
![image](https://github.com/akrherz/live/assets/111789310/c00a4cf4-161c-4568-a73b-adbbf1ea3e65)

**Comment by akrherz** [comment]
I am unsure what to say, I enable writing to some of these rooms and then a few days later, people are back calling each other horrible names/words and I don't want to deal with that.

**Comment by Arch881010** [comment]
Oh! Okay, that makes complete sense. No worries, just wish it was more.. I guess noticeable?
